#ifndef _GLOBALS_H_
#define _GLOBALS_H_

using namespace std;

const int TABDISTANCE = 4;

enum class Token{
    NUL, IDENT, NUMBER, PLUS, MINUS,
    TIMES, SLASH, ODDSYM, EQL, NEQ,
    LSS, LEQ, GTR, GEQ, LPAREN,
    RPAREN, COMMA, SEMICOLON, PERIOD, BECOMES,
    BEGINSYM, ENDSYM, IFSYM, THENSYM, WHILESYM,
    WRITESYM, READSYM, DOSYM, CALLSYM, CONSTSYM,
    VARSYM, PROCSYM, ERROR
};

#endif